--- kernel/Makefile
+++ kernel/Makefile
@@ -145,7 +145,7 @@ $(obj)/config_data.gz: $(obj)/config_data FORCE
 
 filechk_cat = cat $<
 
-$(obj)/config_data: arch/arm64/configs/stock_gki_defconfig FORCE
+$(obj)/config_data: $(KCONFIG_CONFIG) FORCE
 	$(call filechk,cat)
 
 $(obj)/kheaders.o: $(obj)/kheaders_data.tar.xz
